
all: addFavFood addFavNum updateMyName viewBB

addFavFood: addFavFood.c
	cc addFavFood.c -o addFavFood

addFavNum: addFavNum.c
	cc addFavNum.c -o addFavNum

updateMyName: updateMyName.c
	cc updateMyName.c -o updateMyName

viewBB: viewBB.c
	cc viewBB.c -o viewBB
